# Generated by Django 4.2.11 on 2025-11-13 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the debt (e.g., Chase Credit Card)', max_length=200)),
                ('debt_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('student_loan', 'Student Loan'), ('car_loan', 'Car Loan'), ('mortgage', 'Mortgage'), ('personal_loan', 'Personal Loan'), ('medical', 'Medical Debt'), ('other', 'Other')], default='other', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Current balance owed', max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate (%)', max_digits=5)),
                ('minimum_payment', models.DecimalField(decimal_places=2, help_text='Minimum monthly payment', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['balance'],
            },
        ),
    ]
